function data_analysis_script3D_slicesconstant(n,seeds,spacing)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% data_analysis_script3D_slicesconstant(n,seeds,spacing)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Colects the different grain statistics on the 2D slices from 3D
% grain boundary motion. Data files must be stored in the folder
% 'Simulations 3D' as generated by the 'run_simulations3Dconstant'
% function.
%
% INPUT:
%   n = Grid dimension of the simulations
%   seeds = Seeds used to detect the correct file
%   spacing = number of grids in between the 2D slices collected
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

max_epoch = 2;
dims = [n n n];
clearvars -except n seeds spacing max_epoch dims;
file_save = 'data3dconstant-slices';
save(file_save,'-v7.3')
list_t1 = zeros(1,length(seeds));
list_t2 = zeros(1,length(seeds));
areas_grains_slices = cell(length(seeds),max_epoch+1);
areas_convhull_slices = cell(length(seeds),max_epoch+1);
nNeighbors_slices = cell(length(seeds),max_epoch+1);
isopratio_slices = cell(length(seeds),max_epoch+1);
for l = seeds
    filename = ['./Simulations 3D/','simulation3dconstant-',num2str(dims(1)),'x',num2str(dims(2)),'x',num2str(dims(3)),'-',num2str(l),'.mat']
    if exist(filename, 'file') == 2
        disp(l)
        load(filename,'t1_constant','t2_constant')
        list_t1(l) = t1_constant;
        list_t2(l) = t2_constant;
        save_variable(file_save,list_t1,'list_t1')
        save_variable(file_save,list_t2,'list_t2')
        for epoch = 0:max_epoch
            disp(['Compute statistics epoch = ',num2str(epoch)])
            load(filename,['grains_t',num2str(epoch),'_constant']);
            grains = eval(['grains_t',num2str(epoch),'_constant']);
            dt = 2/n^2;
            load(filename,'Rfamilies');
            grains = prep_grains_statistics3d(grains,dims,Rfamilies,dt);
            [areas_grains_slices{l,epoch+1}, areas_convhull_slices{l,epoch+1},...
                nNeighbors_slices{l,epoch+1},isopratio_slices{l,epoch+1}] =...
                compute_statistics_slices3Dconstant(grains,dims,Rfamilies,dt,spacing);

            save_variable(file_save,areas_grains_slices,'areas_grains_slices')
            save_variable(file_save,areas_convhull_slices,'areas_convhull_slices')
            save_variable(file_save,nNeighbors_slices,'nNeighbors_slices')
            save_variable(file_save,isopratio_slices,'isopratio_slices')
        end
        
    end
end

end