function data_analysis_script3Dconstant(n,seeds)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% data_analysis_script3Dconstant(n,seeds)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Colects the different grain statistics from 3D grain boundary
% motion. Data files must be stored in the folder 'Simulations 3D'
% as generated by the 'run_simulations3Dconstant' function.
%
% INPUT:
%   n = Grid dimension of the simulations
%   seeds = Seeds used to detect the correct file
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
max_epoch = 2; % number of intermediate steps stored 
dims = [n n n];
clearvars -except n seeds max_epoch dims;
file_save = 'data3dconstant';
save(file_save,'-v7.3')
list_t1 = zeros(1,length(seeds));
list_t2 = zeros(1,length(seeds));
volumes_grains = cell(length(seeds),max_epoch+1);
volumes_convhull = cell(length(seeds),max_epoch+1);
volumes_grains_alt = cell(length(seeds),max_epoch+1);
volumes_convhull_alt = cell(length(seeds),max_epoch+1);
surface_areas_grains = cell(length(seeds),max_epoch+1);
nNeighbors = cell(length(seeds),max_epoch+1);
for l = seeds
    filename = ['./Simulations 3D/','simulation3dconstant-',num2str(dims(1)),'x',num2str(dims(2)),'x',num2str(dims(3)),'-',num2str(l),'.mat']
    if exist(filename, 'file') == 2
        disp(l)
        load(filename,'t1_constant','t2_constant')
        list_t1(l) = t1_constant;
        list_t2(l) = t2_constant;
        save_variable(file_save,list_t1,'list_t1')
        save_variable(file_save,list_t2,'list_t2')
        for epoch = 0:max_epoch
            disp(['Compute statistics epoch = ',num2str(epoch)])
            load(filename,['grains_t',num2str(epoch),'_constant']);
            grains = eval(['grains_t',num2str(epoch),'_constant']);
            dt = 2/n^2;
            load(filename,'Rfamilies');
            grains = prep_grains_statistics3d(grains,dims,Rfamilies,dt);
            [volumes_grains{l,epoch+1}, volumes_convhull{l,epoch+1},...
                volumes_grains_alt{l,epoch+1}, volumes_convhull_alt{l,epoch+1},...
                surface_areas_grains{l,epoch+1}, nNeighbors{l,epoch+1}]...
                = compute_statistics3Dconstant(grains,dims,dt);
            save_variable(file_save,volumes_grains,'volumes_grains')
            save_variable(file_save,volumes_convhull,'volumes_convhull')
            save_variable(file_save,volumes_grains_alt,'volumes_grains_alt')
            save_variable(file_save,volumes_convhull_alt,'volumes_convhull_alt')
            save_variable(file_save,surface_areas_grains,'surface_areas_grains')
            save_variable(file_save,nNeighbors,'nNeighbors')
        end
        
    end
end

end