function data_analysis_script2Dconstant(n,seeds)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% data_analysis_script2Dconstant(n,seeds)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Colects the different grain statistics from 2D grain boundary
% motion. Data files must be stored in the folder 'Simulations 2D'
% as generated by the 'run_simulations2Dconstant' function.
%
% INPUT:
%   n = Grid dimension of the simulations
%   seeds = Seeds used to detect the correct file
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
max_epoch = 2; % number of intermediate steps stored 
dims = [n n];
clearvars -except n seeds max_epoch dims;
save('data2dconstant','-v7.3')
list_t1 = zeros(1,length(seeds));
list_t2 = zeros(1,length(seeds));
areas_grains = cell(length(seeds),max_epoch+1);
areas_convhull = cell(length(seeds),max_epoch+1);
nNeighbors = cell(length(seeds),max_epoch+1);
isopratio = cell(length(seeds),max_epoch+1);
for l = seeds
    filename = ['./Simulations 2D/','simulation2dconstant-',num2str(dims(1)),'x',num2str(dims(2)),'-',num2str(l),'.mat']
    if exist(filename, 'file') == 2
        disp(l)
        load(filename,'t1_constant','t2_constant')
        list_t1(l) = t1_constant;
        list_t2(l) = t2_constant;
        save_variable('data2dconstant',list_t1,'list_t1')
        save_variable('data2dconstant',list_t2,'list_t2')
        for epoch = 0:max_epoch
            disp(['Compute statistics epoch = ',num2str(epoch)])
            load(filename,['grains_t',num2str(epoch),'_constant']);
            grains = eval(['grains_t',num2str(epoch),'_constant']);
            dt = 2/n^2;
            load(filename,'Rfamilies');
            grains = prep_grains_statistics2d(grains,dims,Rfamilies);
            [areas_grains{l,epoch+1}, areas_convhull{l,epoch+1},...
                nNeighbors{l,epoch+1}, isopratio{l,epoch+1}]...
                = compute_statistics2Dconstant(grains,dims,dt);
            save_variable('data2dconstant',areas_grains,'areas_grains')
            save_variable('data2dconstant',areas_convhull,'areas_convhull')
            save_variable('data2dconstant',nNeighbors,'nNeighbors')
            save_variable('data2dconstant',isopratio,'isopratio')

        end
        
    end
end

end